const express = require('express');
const fs = require('fs');
const { execSync } = require('child_process');

// ─── Config ──────────────────────────────────────────────────────────────────
const CONFIG_FILE  = '/app/data/config.json';
const NGINX_TARGET = '/etc/nginx/conf.d/target.conf';

const DEFAULT_CONFIG = {
  targetHost:   process.env.TARGET_HOST   || 'yoru.midwesteagle.com',
  spoofReferer: process.env.SPOOF_REFERER  || 'https://cineby.sc',
  spoofOrigin:  process.env.SPOOF_ORIGIN   || 'https://cineby.sc',
  apiSecret:    process.env.API_SECRET     || '',
};

function loadConfig() {
  try {
    if (fs.existsSync(CONFIG_FILE)) {
      return { ...DEFAULT_CONFIG, ...JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8')) };
    }
  } catch (_) {}
  return { ...DEFAULT_CONFIG };
}

function saveConfig(cfg) {
  fs.mkdirSync('/app/data', { recursive: true });
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(cfg, null, 2));
}

let config = loadConfig();

// ─── Nginx config generator ─────────────────────────────────────────────────
function writeNginxConfig() {
  const th  = config.targetHost;
  const ref = config.spoofReferer;
  const ori = config.spoofOrigin;

  const conf = `# Auto-generated by stream-proxy API
upstream target_upstream {
    server ${th}:443;
}

server {
    listen 3000 default_server;
    server_name _;

    # API
    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://127.0.0.1:3001;
    }

    # /video.m3u8 — strip 'type' param
    location = /video.m3u8 {
        set $clean_args $is_args$args;
        if ($args ~ ^(.*?)(?:&|^)type=[^&]*(?:&|$)(.*)$) {
            set $clean_args ?$1$2;
        }
        if ($clean_args = ?) {
            set $clean_args;
        }

        proxy_pass https://target_upstream$clean_args;
        proxy_ssl_server_name on;
        proxy_set_header Host ${th};
        proxy_set_header Referer ${ref};
        proxy_set_header Origin ${ori};

        sub_filter 'https://${th}' 'https://$host';
        sub_filter 'http://${th}'  'http://$host';
        sub_filter '${th}'         '$host';
        sub_filter_once off;
        sub_filter_types application/vnd.apple.mpegurl application/x-mpegurl application/mpegurl text/plain text/html application/json application/xml text/vtt application/javascript;

        proxy_hide_header Content-Security-Policy;
        add_header Access-Control-Allow-Origin '*' always;
        add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header Access-Control-Allow-Headers '*' always;
    }

    # Root path
    location = / {
        proxy_pass https://target_upstream$is_args$args;
        proxy_ssl_server_name on;
        proxy_set_header Host ${th};
        proxy_set_header Referer ${ref};
        proxy_set_header Origin ${ori};

        sub_filter 'https://${th}' 'https://$host';
        sub_filter 'http://${th}'  'http://$host';
        sub_filter '${th}'         '$host';
        sub_filter_once off;
        sub_filter_types application/vnd.apple.mpegurl application/x-mpegurl application/mpegurl text/plain text/html application/json application/xml text/vtt application/javascript;

        proxy_hide_header Content-Security-Policy;
        add_header Access-Control-Allow-Origin '*' always;
        add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header Access-Control-Allow-Headers '*' always;
    }

    # Everything else (segments etc.)
    location / {
        proxy_pass https://target_upstream;
        proxy_ssl_server_name on;
        proxy_set_header Host ${th};
        proxy_set_header Referer ${ref};
        proxy_set_header Origin ${ori};

        proxy_redirect https://${th}/ /;
        proxy_redirect http://${th}/  /;

        sub_filter 'https://${th}' 'https://$host';
        sub_filter 'http://${th}'  'http://$host';
        sub_filter '${th}'         '$host';
        sub_filter_once off;
        sub_filter_types application/vnd.apple.mpegurl application/x-mpegurl application/mpegurl text/plain text/html application/json application/xml text/vtt application/javascript;

        proxy_hide_header Content-Security-Policy;
        add_header Access-Control-Allow-Origin '*' always;
        add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header Access-Control-Allow-Headers '*' always;
    }
}
`;
  fs.writeFileSync(NGINX_TARGET, conf);
  console.log(`[NGINX] Config written → ${th}`);
}

function reloadNginx() {
  try {
    execSync('nginx -t 2>&1', { stdio: 'pipe' });
    execSync('nginx -s reload 2>&1', { stdio: 'pipe' });
    console.log('[NGINX] Reloaded OK');
    return true;
  } catch (err) {
    console.error('[NGINX] Reload FAILED:', err.stderr?.toString() || err.message);
    return false;
  }
}

// ─── Express API ─────────────────────────────────────────────────────────────
const app = express();

app.get('/health', (_req, res) => res.json({ status: 'ok' }));

app.get('/api/status', (req, res) => {
  if (config.apiSecret && req.query.secret !== config.apiSecret) {
    return res.status(403).json({ error: 'Invalid or missing ?secret=' });
  }
  res.json({
    targetHost: config.targetHost,
    spoofReferer: config.spoofReferer,
    spoofOrigin: config.spoofOrigin,
  });
});

app.get('/api/new', (req, res) => {
  if (config.apiSecret && req.query.secret !== config.apiSecret) {
    return res.status(403).json({ error: 'Invalid or missing ?secret=' });
  }

  const newDomain = req.query.d;
  if (!newDomain) {
    return res.status(400).json({ error: 'Missing ?d= — usage: /api/new?d=newdomain.com' });
  }

  const oldDomain = config.targetHost;
  config.targetHost = newDomain.replace(/^https?:\/\//, '').replace(/\/+$/, '');
  saveConfig(config);
  writeNginxConfig();

  if (!reloadNginx()) {
    // Rollback on failure
    config.targetHost = oldDomain;
    saveConfig(config);
    writeNginxConfig();
    reloadNginx();
    return res.status(500).json({ error: 'Nginx reload failed, rolled back' });
  }

  res.json({
    success: true,
    previousHost: oldDomain,
    currentHost: config.targetHost,
    message: `Target → ${config.targetHost}`,
  });
});

// ─── Boot ────────────────────────────────────────────────────────────────────
writeNginxConfig();

app.listen(3001, '127.0.0.1', () => {
  console.log(`[API] Sidecar on :3001 | Target: ${config.targetHost}`);
});
