version: "3.8"

services:
  stream-proxy:
    build: .
    container_name: stream-proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TARGET_HOST=yoru.midwesteagle.com
      - SPOOF_REFERER=https://cineby.sc
      - SPOOF_ORIGIN=https://cineby.sc
      - API_SECRET=
    volumes:
      - proxy-data:/app/data

volumes:
  proxy-data:
